### ISSUE TITLE
Замечания лаб3 @Kerpee

### ISSUE THREAD

**Issue by ananasn** [Kerpee/Lab3#1]
@Kerpee

 
 * Использование в функциях глобальных переменных  плохая практика. Лучше стараться сделать функцию [чистой](https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D1%81%D1%82%D0%BE%D1%82%D0%B0_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8).  Передавайте объекты, которые вы хотите модифицировать, явно через параметры функции. Для этого можно использовать lambda-функцию: ```command = lambda: generate_key(input_entry.get(), label))```
* Сделайте размер окна константами.  
* Вот так не делайте ```from tkinter import * ```, перечислите все что импортируете

**Comment by Kerpee** [comment]
Выложил исправленный вариант.
